"""add guest name to upload

Revision ID: 79999376ab0a
Revises: 9666e1af9256
Create Date: 2026-05-25 19:15:24.953490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79999376ab0a'
down_revision: Union[str, None] = '9666e1af9256'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploads', sa.Column('guest_name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uploads', 'guest_name')
    # ### end Alembic commands ###
