"""Add media_type to Upload

Revision ID: 9666e1af9256
Revises: 58921ab03043
Create Date: 2026-05-21 16:13:06.077699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9666e1af9256'
down_revision: Union[str, None] = '58921ab03043'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploads', sa.Column('media_type', sa.String(length=20), server_default='photo', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uploads', 'media_type')
    # ### end Alembic commands ###
